import type { PlanFeatures } from '../types/billing';

export const PLAN_TIERS: Record<string, PlanFeatures> = {
  starter: {
    name: 'Starter',
    pricePerMonth: 149,
    includedMinutes: 200,
    overageRatePerMinute: 0.35,
    maxAgents: 1,
    voiceCloning: false,
    mlsIntegration: true,
    crmSync: true,
    callRecordingRetentionDays: 30,
    whiteLabel: false,
    mfa: false,
  },
  professional: {
    name: 'Professional',
    pricePerMonth: 299,
    includedMinutes: 600,
    overageRatePerMinute: 0.30,
    maxAgents: 1,
    voiceCloning: true,
    mlsIntegration: true,
    crmSync: true,
    callRecordingRetentionDays: 90,
    whiteLabel: false,
    mfa: true,
  },
  growth: {
    name: 'Growth',
    pricePerMonth: 499,
    includedMinutes: 1500,
    overageRatePerMinute: 0.25,
    maxAgents: 3,
    voiceCloning: true,
    mlsIntegration: true,
    crmSync: true,
    callRecordingRetentionDays: 365,
    whiteLabel: 'subdomain',
    mfa: true,
  },
  agency: {
    name: 'Agency',
    pricePerMonth: 999,
    includedMinutes: 4000,
    overageRatePerMinute: 0.20,
    maxAgents: 'unlimited',
    voiceCloning: true,
    mlsIntegration: true,
    crmSync: true,
    callRecordingRetentionDays: 'unlimited',
    whiteLabel: 'full',
    mfa: true,
  },
} as const;

export const ADD_ONS = {
  additionalAgent: { name: 'Additional Agent', pricePerMonth: 79 },
  extraMinutesBundle: { name: 'Extra 200 Minutes Bundle', price: 49, minutes: 200 },
  additionalVoiceClone: { name: 'Voice Clone (additional voice)', pricePerMonth: 29 },
  smsOverage: { name: 'SMS confirmations (beyond 100/mo)', pricePerMessage: 0.03 },
  additionalPhoneNumber: { name: 'Dedicated phone number', pricePerMonth: 5 },
} as const;
